{
 "title": "A-VENT Digital Twin Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "A-VENT",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"NODE_RED\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"timestamp\" and\r\n    r._field == \"value\"\r\n  )"
    }
   ]
  },
  {
   "title": "Ventilator Waveform Graph",
   "type": "timeseries",
   "description": "Real-time pressure, flow rate, tidal volume curves",
   "gridPos": { "h": 12, "w": 16, "x": 6, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"waveform\" and\r\n    r._field == \"Air Flow\"\r\n  )"
    },
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"waveform\" and\r\n    r._field == \"Pressure\"\r\n  )"
    },
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"waveform\" and\r\n    r._field == \"Tidal Volume\"\r\n  )"
    }
   ]
  },
  {
   "title": "PIP",
   "type": "stat",
   "description": "Peak Inspiratory Pressure",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"High Pressure\"\r\n  )"
    }
   ]
  },
  {
   "title": "PEEP",
   "type": "stat",
   "description": "Positive End Expiratory Pressure",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"Low Pressure\"\r\n  )"
    }
   ]
  },
  {
   "title": "RR (min)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"Low Respiration\"\r\n  )"
    }
   ]
  },
  {
   "title": "RR (max)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"High Respiration\"\r\n  )"
    }
   ]
  },
  {
   "title": "TD (min)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"Low Volume\"\r\n  )"
    }
   ]
  },
  {
   "title": "TD (max)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"threshold\" and\r\n    r._field == \"High Volume\"\r\n  )"
    }
   ]
  },
  {
   "title": "Machine Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"MachineStatus\"\r\n\tFROM public.aventdb;"
    }
   ]
  },
  {
   "title": "PATIENT",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cmH2O" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"curvetracker\" and\r\n    r._field == \"PIP\" or r._field == \"PEEP\"\r\n  )"
    }
   ]
  },
  {
   "title": "TD",
   "type": "bargauge",
   "description": "Tidal Volume",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"curvetracker\" and\r\n    r._field == \"Peak Volume\"\r\n  )"
    }
   ]
  },
  {
   "title": "RR",
   "type": "bargauge",
   "description": "Respiratory Rate",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"curvetracker\" and\r\n    r._field == \"Respiratory Rate\"\r\n  )"
    }
   ]
  },
  {
   "title": "Pressure Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"PressureStatus\"\r\n\tFROM public.aventdb;"
    }
   ]
  },
  {
   "title": "Spo2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"oximeter\" and\r\n    r._field == \"SpO2\"\r\n  )"
    }
   ]
  },
  { "title": "Pulse Oximeter", "type": "pierosavi-imageit-panel", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 } },
  {
   "title": "PVA Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"AsynchronyStatus\"\r\n\tFROM public.aventdb;"
    }
   ]
  },
  {
   "title": "Respiratory Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"RespirationStatus\"\r\n\tFROM public.aventdb;"
    }
   ]
  },
  {
   "title": "Pulse Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"oximeter\" and\r\n    r._field == \"Pulse Rate\"\r\n  )"
    }
   ]
  },
  {
   "title": "Anomaly Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"AnomalyStatus\"\n\tFROM public.aventdb;\n"
    }
   ]
  },
  {
   "title": "Volume Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"VolumeStatus\"\r\n\tFROM public.aventdb;"
    }
   ]
  },
  {
   "title": "PI",
   "type": "stat",
   "description": "Perfusion Index",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AVENT\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"oximeter\" and\r\n    r._field == \"Perfusion Index\"\r\n  )"
    }
   ]
  }
 ]
}